name: Analyze

on: workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Clone the repository
        run: |
          rm -rf parcours-hybridation
          git clone https://github.com/LUniversiteNumerique/parcours-hybridation.git
      - run: ruby main.rb
      - name: Commit report
        run: |
          git checkout -b 'report'
          git config --global user.name 'Report'
          git config --global user.email 'report@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push --set-upstream origin report
